apiVersion: v1
kind: ConfigMap
metadata:
  namespace: hoteler-namespace
  name: hoteler-web-react-config
data:
  backend_url: http://127.0.0.1:8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hoteler-namespace
  name: hoteler-web-react
  labels:
    app:  hoteler-web-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hoteler-web-react
  template:
    metadata:
      labels:
        app: hoteler-web-react
      name: hoteler-web-react
    spec:
      containers:
        - name: hoteler-web-react
          image: hoteler-web-react
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: hoteler-web-react-config
                  key: backend_url
---
apiVersion: v1
kind: Service
metadata:
  namespace: hoteler-namespace
  name: hoteler-web-react
  labels:
    app:  hoteler-web-react
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  type: NodePort
  selector:
    app: hoteler-web-react
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: hoteler-namespace
  name: hoteler-web-react
spec:
  rules:
  - host: hoteler-react.damingerdai.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hoteler-web-react
            port:
              number: 80
