[build]
  base = ""
  publish = "build"
  command = "pnpm run build"

[[headers]]
  for = "/*"

  [headers.values]
    cache-control = "max-age=7200"


[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = "max-age=31536000"
[[redirects]]
  from = "/*"
  to = "index.html"
  status = 404
[[redirects]]
  from = "/api/*"
  to = "https://hoteler-react.damingerdai.com/:splat"
  status = 200
  force = true
  query = {path = ":path"}


